--- Autogenerated engine entrypoint script

require("core.registration")

Registration.compilation(function()
    local result = CompilationResult.new()
        result:namespace {
            id = "generated",
            items = {},
            scripts = {},
            components = {},
            intents = {}
        }
        return result
end)