--- Autogenerated engine entrypoint script.
--- Do not change the value of package.path

require("core.registration")

compilation(function()
    local result = CompilationResult.new()
    result:namespace {
        id = "generated",
        items = {},
        scripts = {},
        components = {},
        intents = {}
    }
    return result
end)