package org.lain.engine.client.resources

import com.google.gson.JsonArray
import com.google.gson.JsonObject
import com.google.gson.JsonParseException
import de.javagl.obj.Mtl
import de.javagl.obj.Obj
import net.minecraft.client.renderer.block.model.ItemTransform
import net.minecraft.client.resources.model.Material
import net.minecraft.resources.ResourceLocation
import org.joml.Vector3f
import org.joml.Vector3fc
import org.lain.engine.client.EngineClient
import org.lain.engine.client.mc.JsonMc
import org.lain.engine.client.mc.missingSpriteId
import org.lain.engine.mc.engineId
import org.lain.engine.util.Timestamp
import org.lain.engine.util.injectValue
import org.slf4j.LoggerFactory

/**
 * Возвращает идентификатор файлового ассета относительно `engine/assets` без расширения
 */
fun Asset.prepareIdentifier(): String {
    val ext = this.relative.extension
    return this.relative.normalize().toString()
        .normalizeSlashes()
        .let {
            if (!ext.isEmpty()) it.dropLast(ext.count() + 1) else it
        }
}

fun String.normalizeSlashes() = replace('\\', '/')

fun String.toEngineIdentifier(): ResourceLocation = engineId(this)

sealed class EngineItemAsset {
    data class Generated(val texture: EngineTexture, val type: String) : EngineItemAsset() {
        val registrationId = texture.asset
            .prepareIdentifier()
            .replaceFirst("tex", "autogen")
            .toEngineIdentifier()
    }

    data class FileDefinition(val asset: Asset, val json: JsonObject) : EngineItemAsset() {
        val registrationId = asset
            .prepareIdentifier()
            .replace(".asset", "")
            .toEngineIdentifier()
    }
}

data class EngineItemJsonModel(
    val asset: Asset,
    val type: ModelType,
    val json: JsonObject
) {
    val registrationId by lazy {
        asset
            .prepareIdentifier()
            .toEngineIdentifier()
    }
}

data class EngineObjModel(
    val asset: Asset,
    val obj: Obj,
    val mtl: Map<String, Mtl>
)

enum class ModelType {
    JSON, OBJ;
}

internal val LOGGER = LoggerFactory.getLogger("Engine Model Loader")
internal val MISSING_SPRITE = Material(ITEMS_ATLAS, missingSpriteId)

data class ResourceList(
    // Спрайт атлас -> текстуры
    val textureAssets: Map<String, List<EngineTexture>>,
    val itemModels: List<EngineItemJsonModel>,
    val itemAssets: List<EngineItemAsset.FileDefinition>,
    val generatedItemAssets: List<EngineItemAsset.Generated>,
    val objModels: Map<String, EngineObjModel>
) {
    val allItemAssets = itemAssets + generatedItemAssets
}

fun findAssets(client: EngineClient): ResourceList {
    val start = Timestamp()
    val resources = client.resources
    val assets = resources.assets
    val spriteAtlasRules = assets.spriteAtlases
    val spriteAtlasDirectories = spriteAtlasRules.directories.map { it.key to legacyAtlasName(it.value) }
    val defaultAtlas = legacyAtlasName(spriteAtlasRules.default)

    val itemsAssets = mutableListOf<EngineItemAsset.FileDefinition>()
    val itemModels = mutableListOf<EngineItemJsonModel>()
    val textures = mutableMapOf<String, MutableMap<String, EngineTexture>>()
    val wallpapersTextures = mutableMapOf<String, EngineTexture>()
    val objModels = mutableMapOf<String, EngineObjModel>()
    val autogenerated = mutableListOf<EngineItemAsset.Generated>()

    fun textureAtlasList(atlas: String) = textures.getOrPut(atlas) { mutableMapOf() }

    assets.browseAssets { relative, file, packer ->
        val ext = file.extension
        val isJson = ext == "json"

        try {
            if (isJson) {
                val asset = packer()
                val reader = file.reader()
                val json = JsonMc.parse(reader)
                if (file.nameWithoutExtension.endsWith(".asset")) {
                    json.substituteEngineRelativePathItemAsset(asset)
                    itemsAssets += EngineItemAsset.FileDefinition(packer(), json)
                } else {
                    val isObj = json.has("obj") && json.getAsJsonPrimitive("obj").asBoolean
                    var modelType: ModelType
                    when (isObj) {
                        true -> {
                            json.substituteEngineRelativePathObj(asset)
                            modelType = ModelType.OBJ
                        }

                        false -> {
                            json.substituteEngineRelativePathJson(asset)
                            json.ensureParticleTextureReference()
                            modelType = ModelType.JSON
                        }
                    }
                    itemModels += EngineItemJsonModel(asset, modelType, json)
                }
                reader.close()
            } else if (ext == "obj") {
                val asset = packer()
                val obj = parseObjModel(asset)
                obj.mtl.forEach { (key, mtl) ->
                    if (mtl.mapKd == null) return@forEach
                    mtl.mapKd = mtl.mapKd.substituteEngineRelativePath(asset).replace(".png", "")
                }
                objModels[relative] = obj

            } else if (ext == "png") {
                val atlas = spriteAtlasDirectories.lastOrNull { (directory, _) ->
                    relative.startsWith(directory)
                }?.second
                textureAtlasList(atlas ?: defaultAtlas)[relative] = EngineTexture(packer())
            }
        } catch (e: Throwable) {
            LOGGER.error("При загрузке ресурса ${file.path} возникла ошибка", e)
        }
    }

    resources.autogenerationItemAssets.autogen.forEach {
        autogenerated += EngineItemAsset.Generated(
            textureAtlasList(defaultAtlas)[it.assetPath] ?: return@forEach,
            it.type
        )
    }

    LOGGER.info("Ресурсы обработаны за {} мл.", start.timeElapsed())

    return ResourceList(
        textures.toMap().mapValues { it.value.values.toList() },
        itemModels,
        itemsAssets,
        autogenerated,
        objModels
    )
}

fun String.substituteEngineRelativePath(relative: String) = replaceFirst("~/", "$relative/")

fun String.substituteEngineRelativePath(asset: Asset) = replace("~/", "${asset.relativeParent.path.normalizeSlashes()}/")

fun JsonObject.substituteEngineRelativePathItemAsset(asset: Asset) {
    val model = getAsJsonObject("model")
    model.addProperty(
        "model",
        model.getAsJsonPrimitive("model").asString.substituteEngineRelativePath(asset)
    )
}

fun JsonObject.substituteEngineRelativePathObj(asset: Asset) {
    addProperty(
        "model",
        getAsJsonPrimitive("model").asString.substituteEngineRelativePath(asset)
    )
}

fun JsonObject.substituteEngineRelativePathJson(asset: Asset) {
    val textures = getAsJsonObject("textures")
    textures.entrySet().forEach { (key, path) ->
        val pathString = path.asString
        textures.addProperty(key, pathString.substituteEngineRelativePath(asset))
    }
}

fun JsonObject.ensureParticleTextureReference() {
    val textures = getAsJsonObject("textures")
    if (!textures.has("particle") && !textures.isEmpty) {
        textures.addProperty("particle", textures.entrySet().first().value.asString)
    }
}

fun parseEngineItemAssets(
    assets: List<EngineItemAsset>,
): Map<ResourceLocation, EngineItemDefinition> {
    val contents = mutableMapOf<ResourceLocation, EngineItemDefinition>()
    val start = Timestamp()
    for (item in assets) {
        when(item) {
            is EngineItemAsset.FileDefinition -> {
                val asset = item.asset

                try {
                    val modelObject = item.json.getAsJsonObject("model")
                    val modelType = JsonMc.getAsString(modelObject, "type")
                    if (modelType != "minecraft:model") {
                        throw JsonParseException("Unsupported item model type on Minecraft 1.21.1: $modelType")
                    }
                    val model = ResourceLocation.parse(JsonMc.getAsString(modelObject, "model"))

                    val disableCulling = JsonMc.getAsBoolean(item.json, "disable_culling", false)
                    val markers = mutableMapOf<String, Vector3fc>()
                    if (item.json.has("markers")) {
                        JsonMc.getAsJsonObject(item.json, "markers")
                            .entrySet()
                            .forEach { (key, value) ->
                                markers[key] = deserializeVec3f(value.asJsonArray)
                            }
                    }
                    var transformationOutfit: ItemTransform? = null
                    if (item.json.has("transformation_outfit")) {
                        transformationOutfit = parseTransformation(item.json.get("transformation_outfit"))
                    }
                    contents[item.registrationId] = EngineItemDefinition(
                        asset,
                        model,
                        disableCulling,
                        markers,
                        transformationOutfit
                    )
                } catch (e: Throwable) {
                    LOGGER.error("При загрузке ассета предмета ${asset.relativeString} возникла ошибка", e)
                }
            }
            is EngineItemAsset.Generated -> {
                contents[item.registrationId] = EngineItemDefinition(
                    item.texture.asset,
                    item.registrationId,
                    false,
                    emptyMap(),
                    null
                )
            }
        }
    }
    LOGGER.info("Ассеты предметов сгенерированы за {} мл.", start.timeElapsed())
    return contents
}

fun deserializeVec3f(jsonArray: JsonArray): Vector3fc {
    if (jsonArray.size() != 3) {
        throw JsonParseException("Expected 3 values, found: " + jsonArray.size());
    }
    val fs = jsonArray.map { it.asFloat }
    return Vector3f(fs[0], fs[1], fs[2])
}

private fun legacyAtlasName(name: String): String = if (name == "items") "blocks" else name
