[versions]
minecraft = "1.21.11"
kotlin = "2.4.0"

# Fabric
fabric-loader = "0.19.3"
fabric-api = "0.141.4+1.21.11"
fabric-kotlin = "1.13.12+kotlin.2.4.0"

# Build tools
loom = "1.16-SNAPSHOT"
shadow = "9.3.0"

# Library mods
graphene = "1.7.2"
adventure = "6.8.0"
yaml-config = "19.1.0-fabric"
ui-lib = "19.1.0-fabric"
architectury-api = "19.0.1+fabric"
permissions-api = "0.6.1"
female-gender = "5.0.0-Beta.3+1.21.11"

# Libraries
cyberia-version = "1.8"
cyberia-ecs-api = "1.3.4"
exposed = "1.0.0"
sqlite = "3.51.1.0"
luaj = "3.0.1"
kaml = "0.104.0"
obj = "0.4.0"
reflections = "0.10.2"
protobuf = "1.9.0"
credential-secure-storage = "1.0.3"

# Mod compatibility
camera-overhaul = "2.0.6-fabric+mc.1.21.11-plus"
lambdynlights = "4.9.1+1.21.11"
worldedit = "7.4.2"

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }
fabric-loader-junit = { module = "net.fabricmc:fabric-loader-junit", version.ref = "fabric-loader" }

graphene = { module = "io.github.trethore:graphene-ui", version.ref = "graphene" }
yaml = { module = "maven.modrinth:yaml-config", version.ref = "yaml-config" }
ui = { module = "maven.modrinth:ui-lib", version.ref = "ui-lib" }
architectury = { module = "maven.modrinth:architectury-api", version.ref = "architectury-api" }
adventure = { module = "net.kyori:adventure-platform-fabric", version.ref = "adventure" }
permissions = { module = "me.lucko:fabric-permissions-api", version.ref = "permissions-api" }
female-gender = { module = "maven.modrinth:female-gender", version.ref = "female-gender" }

camera-overhaul = { module = "maven.modrinth:cameraoverhaul", version.ref = "camera-overhaul" }
lambdynlights-api = { module = "dev.lambdaurora.lambdynamiclights:lambdynamiclights-api", version.ref = "lambdynlights" }
lambdynlights-runtime = { module = "dev.lambdaurora.lambdynamiclights:lambdynamiclights-runtime", version.ref = "lambdynlights" }
worldedit-api = { module = "com.sk89q.worldedit:worldedit-core", version.ref = "worldedit" }
worldedit-fabric = { module = "com.sk89q.worldedit:worldedit-fabric-mc1.21.11", version.ref = "worldedit" }

cyberia = { module = "org.lain.cyberia:fabric", version.ref = "cyberia-version" }
cyberia-ecs-api = { module = "org.lain.cyberia:ecs-api", version.ref = "cyberia-ecs-api" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
luaj = { module = "org.luaj:luaj-jse", version.ref = "luaj" }
reflections = { module = "org.reflections:reflections", version.ref = "reflections" }
obj = { module = "de.javagl:obj", version.ref = "obj" }
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }
protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "protobuf" }
credential-secure-storage = { module = "com.microsoft:credential-secure-storage", version.ref = "credential-secure-storage" }

[bundles]
fabric = ["fabric-api", "fabric-kotlin", "fabric-loader"]
compat = ["camera-overhaul", "lambdynlights-api", "worldedit-api", "worldedit-fabric"]
libraries = ["exposed-core", "exposed-jdbc", "sqlite-jdbc", "luaj", "reflections", "obj", "kaml", "protobuf", "credential-secure-storage"]
